// public/app.js
const API_BASE = '/api/qr';

async function api(path, opts = {}) {
  const res = await fetch(API_BASE + path, opts);
  return res.json();
}

function el(html) {
  const div = document.createElement('div');
  div.innerHTML = html;
  return div.firstElementChild;
}

async function generateBasic() {
  const url = document.getElementById('urlInput').value.trim();
  if (!url) return alert('Enter URL');
  const res = await fetch('/api/qr/basic', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url }) });
  const data = await res.json();
  if (data.ok) {
    showResult(data.url, data.filename);
    loadHistory();
  } else {
    alert('Error: ' + (data.error || JSON.stringify(data)));
  }
}

async function generateAdvanced() {
  const url = document.getElementById('urlInput').value.trim();
  if (!url) return alert('Enter URL');
  const watermarkText = document.getElementById('watermarkInput').value.trim();
  const res = await fetch('/api/qr/advanced', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url, watermarkText }) });
  const data = await res.json();
  if (data.ok) {
    showResult(data.url, data.filename);
    loadHistory();
  } else {
    alert('Error: ' + (data.error || JSON.stringify(data)));
  }
}

function showResult(imgUrl, filename) {
  const result = document.getElementById('result');
  result.innerHTML = `
    <div class="mt-3 border rounded p-3 bg-black/30">
      <img src="${imgUrl}" class="max-w-full mb-3 rounded" />
      <div class="flex gap-3">
        <a href="${imgUrl}" target="_blank" class="px-3 py-2 bg-[var(--accent)] rounded text-white">Open</a>
        <button onclick="sendTelegram('${filename}')" class="px-3 py-2 bg-slate-800 rounded">Send to Telegram</button>
      </div>
    </div>
  `;
}

async function loadHistory() {
  const res = await fetch('/api/qr/list');
  const data = await res.json();
  if (!data.ok) return;
  const container = document.getElementById('history');
  container.innerHTML = '';
  data.items.forEach(it => {
    const item = el(`
      <div class="p-3 rounded border bg-black/20 flex items-center justify-between">
        <div>
          <div class="font-medium">${it.url}</div>
          <div class="text-xs text-slate-400">${new Date(it.createdAt).toLocaleString()} • ${it.size?.toLocaleString() || '?'} bytes</div>
        </div>
        <div class="flex items-center gap-2">
          <a href="/uploads/${it.filename}" target="_blank" class="px-2 py-1 rounded bg-slate-700 text-sm">View</a>
          <button onclick="sendTelegram('${it.filename}')" class="px-2 py-1 rounded bg-[var(--accent)] text-sm text-white">Telegram</button>
        </div>
      </div>
    `);
    container.appendChild(item);
  });
}

async function sendTelegram(filename) {
  const caption = prompt('Caption for Telegram send (optional):', 'Generated by PUJO DEV');
  const res = await fetch('/api/qr/send', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ filename, caption }) });
  const data = await res.json();
  if (data.ok) alert('Sent to Telegram!');
  else alert('Telegram error: ' + (data.error || JSON.stringify(data)));
}

document.getElementById('btnBasic').addEventListener('click', generateBasic);
document.getElementById('btnAdvanced').addEventListener('click', generateAdvanced);
document.getElementById('refreshList').addEventListener('click', loadHistory);

(async function init() {
  try {
    const health = await fetch('/api/health').then(r => r.json());
    document.getElementById('serverStatus').innerText = 'Server ok ' + new Date(health.time).toLocaleString();
  } catch(e) {
    document.getElementById('serverStatus').innerText = 'Server unreachable';
  }
  loadHistory();
})();